# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Musique de casque
tagline:             ''
description:         ''
url:                 http://musiquedecasque.fr
baseurl:             ''
paginate:            1
